Add option to install plain OMNI

diff --git a/install b/install
--- a/install
+++ b/install
@@ -35,6 +35,7 @@ with_jdk=false
 with_ant=false
 with_claw=false
 claw_install_env=""
+with_omni=false
 with_ofp=false
 with_docs=false
 with_dace=true
@@ -61,6 +62,7 @@ print_usage_with_options() {
   echo "  --with[out]-jdk              Install JDK instead of using system version (default: use system version)"
   echo "  --with[out]-ant              Install ant instead of using system version (default: use system version)"
   echo "  --with[out]-claw             Install CLAW and OMNI Compiler (default: disabled)"
+  echo "  --with[out]-omni             Install OMNI Compiler; cannot be combined with --with-claw (default: disabled)"
   echo "  --with[out]-ofp              Install Open Fortran Parser (default: disabled)"
   echo "  --with[out]-dace             Install DaCe (default: enabled)"
   echo "  --with[out]-tests            Install dependencies to run tests (default: enabled)"
@@ -137,6 +139,12 @@ while getopts "$optspec" optchar; do
         without-claw) # Disable installation of OMNI+CLAW
           with_claw=false
           ;;
+        with-omni)   # Enable installation of OMNI
+          with_omni=true
+          ;;
+        without-omni) # Disable installation of OMNI
+          with_omni=false
+          ;;
         with-dace)    # Enable installation of DaCe
           with_dace=true
           ;;
@@ -189,6 +197,13 @@ while getopts "$optspec" optchar; do
   esac
 done
 
+if [ "$with_omni" == true ]; then
+  if [ "$with_claw" == true ]; then
+    echo "ERROR: Cannot combine --with-claw and --with-omni"
+    exit 1
+  fi
+fi
+
 # Print configuration
 if [ "$verbose" == true ]; then
   print_step "Installation configuration:"
@@ -198,6 +213,7 @@ if [ "$verbose" == true ]; then
   [[ "$with_jdk" == true ]]  && echo "    --with-jdk"
   [[ "$with_ant" == true ]]  && echo "    --with-ant"
   [[ "$with_claw" == true ]] && echo "    --with-claw"
+  [[ "$with_omni" == true ]] && echo "    --with-omni"
   [[ "$with_ofp" == false ]] && echo "    --without-ofp"
   [[ "$with_dace" == false ]] && echo "    --without-dace"
   [[ "$with_tests" == false ]] && echo "    --without-tests"
@@ -205,7 +221,6 @@ if [ "$verbose" == true ]; then
   [[ "$with_examples" == false ]] && echo "    --without-examples"
   [[ "$proxy_certificate" != "" ]] && echo "    --proxy-certificate='$proxy_certificate'"
   [[ "$jdk_certificate" != "" ]]   && echo "    --jdk-certificate='$jdk_certificate'"
-  [[ "$claw_install_env" != "" ]]  && echo "    --claw_install_env='$claw_install_env'"
 fi
 
 if [ "x$proxy_certificate" != "x" ]; then
@@ -397,6 +412,28 @@ if [ "$with_claw" == true ]; then
 fi
 
 #
+# Install OMNI
+#
+
+if [ "$with_omni" == true ]; then
+  print_step "Downloading and installing OMNI Compiler"
+
+  OMNI_INSTALL_DIR=${venv_path}/opt/omni
+  mkdir -p "${OMNI_INSTALL_DIR}"
+  cd "${OMNI_INSTALL_DIR}"
+  rm -rf xcodeml-tools
+  git clone --recursive --single-branch https://github.com/omni-compiler/xcodeml-tools.git xcodeml-tools
+
+  cd xcodeml-tools
+
+  omni_opts=()
+  [[ ! -z "${JAVA_HOME}" ]] && omni_opts+=("JAVA_HOME=${JAVA_HOME}")
+
+  ./configure --prefix="${OMNI_INSTALL_DIR}" "${omni_opts[@]}"
+  make && make install
+fi
+
+#
 # Install OFP
 #
 
@@ -494,6 +531,11 @@ fi
 # Inject CLAW into env
 if [ "$with_claw" == true ]; then
   path_var=${CLAW_INSTALL_DIR}/bin:$path_var
+fi
+
+# Inject OMNI into env
+if [ "$with_omni" == true ]; then
+  path_var=${OMNI_INSTALL_DIR}/bin:$path_var
 fi
 
 # Update path variable
